/**
 * Schema integration tests.
 * Uses better-sqlite3 (in-memory) instead of bun:sqlite so Vitest (Node) can run these.
 * The SQL generated by Drizzle is identical for both drivers.
 */
import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { drizzle } from 'drizzle-orm/better-sqlite3';
import { migrate } from 'drizzle-orm/better-sqlite3/migrator';
import Database from 'better-sqlite3';
import { join } from 'node:path';
import { users } from './schema/users.ts';
import { matchRecords } from './schema/match_records.ts';
import { detectedEvents } from './schema/detected_events.ts';
import { optOuts } from './schema/opt_outs.ts';

const MIGRATIONS_FOLDER = join(process.cwd(), 'drizzle');

function makeTestDb() {
  const sqlite = new Database(':memory:');
  sqlite.exec('PRAGMA foreign_keys=ON;');
  const db = drizzle(sqlite);
  migrate(db, { migrationsFolder: MIGRATIONS_FOLDER });
  return { db, sqlite };
}

describe('DB schema', () => {
  let db: ReturnType<typeof makeTestDb>['db'];
  let sqlite: ReturnType<typeof makeTestDb>['sqlite'];

  beforeEach(() => {
    ({ db, sqlite } = makeTestDb());
  });

  afterEach(() => {
    sqlite.close();
  });

  it('inserts user → match_record → detected_event successfully', () => {
    // Insert a user
    db.insert(users).values({
      telegram_id: 123456,
      telegram_username: 'testuser',
      riot_puuid: 'puuid-abc-123',
      riot_name: 'Player',
      riot_tag: 'TAG',
    }).run();

    // Insert a match_record
    db.insert(matchRecords).values({
      riot_puuid: 'puuid-abc-123',
      match_id: 'match-001',
      started_at: Date.now(),
      map: 'Ascent',
      agent: 'Jett',
      kills: 20,
      deaths: 10,
      assists: 5,
      result: 'win',
      rounds_played: 25,
      kill_events_compact: '[]',
    }).run();

    // Insert a detected_event
    db.insert(detectedEvents).values({
      event_type: 'ace',
      riot_puuid: 'puuid-abc-123',
      match_id: 'match-001',
      payload_json: '{"round":5,"weapon":"Vandal"}',
    }).run();

    // Verify data is present
    const userRows = db.select().from(users).all();
    expect(userRows).toHaveLength(1);
    expect(userRows[0]?.riot_puuid).toBe('puuid-abc-123');

    const matchRows = db.select().from(matchRecords).all();
    expect(matchRows).toHaveLength(1);
    expect(matchRows[0]?.result).toBe('win');

    const eventRows = db.select().from(detectedEvents).all();
    expect(eventRows).toHaveLength(1);
    expect(eventRows[0]?.event_type).toBe('ace');
    expect(eventRows[0]?.status).toBe('pending');
  });

  it('enforces UNIQUE constraint on (match_id, event_type, riot_puuid)', () => {
    // Insert user
    db.insert(users).values({
      telegram_id: 789,
      riot_puuid: 'puuid-xyz-456',
    }).run();

    // Insert first event
    db.insert(detectedEvents).values({
      event_type: 'clutch_1vN',
      riot_puuid: 'puuid-xyz-456',
      match_id: 'match-002',
      payload_json: '{"n":3}',
    }).run();

    // Duplicate insert should throw
    expect(() => {
      db.insert(detectedEvents).values({
        event_type: 'clutch_1vN',
        riot_puuid: 'puuid-xyz-456',
        match_id: 'match-002',
        payload_json: '{"n":5}',
      }).run();
    }).toThrow();
  });

  it('inserts opt_out with FK CASCADE from users', () => {
    db.insert(users).values({
      telegram_id: 555,
      riot_puuid: null,
    }).run();

    db.insert(optOuts).values({
      telegram_id: 555,
      chat_realtime_disabled: 1,
    }).run();

    const rows = db.select().from(optOuts).all();
    expect(rows).toHaveLength(1);
    expect(rows[0]?.chat_realtime_disabled).toBe(1);
  });
});
